#include <stdio.h>
#include <windows.h>
#include <stdlib.h>
#include <string.h>
#define DEF_STRING_GROUP 1
#define DEF_INTEGER_GROUP 1

#if DEF_INTEGER_GROUP
	#define	TMPLEN 	2000
	#define	MAX 	200
	#define	MIN 	100
	#define	ONELINE	140
#endif
#if DEF_STRING_GROUP
	#define N_REG_TXT		"\"reg.txt\" 파일을 열 수 없습니다!"
	#define REG_TXT			"reg.txt"
	#define N_RESULT_TXT	"\"result.txt\" 파일을 열 수 없습니다!"
	#define RESULT_TXT		"result.txt"
	#define N_CMD_BAT		"\"cmd.bat\" 파일을 열 수 없습니다!"
	#define CMD_BAT			"cmd.bat"
	#define CMD_BAT_NUL		"cmd.bat > nul"
	#define NO_AD_PROG		"광고프로그램이 탐지 되지 않았습니다."
	#define TITLE			"killads_Made By. ParkJG"
	#define CMD_TITLE		"title killads"
	#define CONFIRM_PROG	" 개의 프로그램이 확인되었습니다."
	#define CMP_PROG		"설치 프로그램 비교중....\n\n"
	#define CMF_PROG		"프로그램 정보 확인중...\n"
	#define INSP_COMPLETE	"\n\n검사 완료!\n\n\n"
	#define NEW_RESULT_TXT	"fsutil file createnew result.txt 0 > nul"
	#define NEW_CMD_BAT		"fsutil file createnew cmd.bat 0 > nul"
	#define OPT_PROG		"프로그램을 최적화 하시겠습니까?"
	#define CAN_PROG		"프로그램을 취소합니다."
	#define EXTR_PROG_LIST	"프로그램 목록 추출중...\n"
	#define REG64			"reg query \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\" /s /reg:64 > reg.txt"
	#define REG32			"reg query \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\" /s /reg:32 >> reg.txt"
	#define REG_PRODUCTS	"reg query \"HKCR\\Installer\\Products\" /s >> reg.txt"
	#define DEL_RESULT_TXT	"del result.txt > nul"
	#define DEL_REG_TXT		"del reg.txt > nul"
	#define DEL_CMD_BAT		"del cmd.bat > nul"
	#define FIND_STR		"    DisplayName    REG_SZ    "
	#define FIND_STR2		"    DisPlayName    REG_SZ    "
	#define CHG_BEFORE		"    DisplayName"
	#define CHG_BEFORE2		"    DisPlayName"
	#define CHG_AFTER		" - ProgramName : "
	#define PROG_LIST		"프로그램 리스트"
	#define UNINS			"UninstallString    REG_SZ"
	#define QUNINS			"QuietUninstallString    REG_SZ"
	#define CONFIRM_N_PROG	"\n%d개의 프로그램이 확인 됨.\n"
	#define DETECT_AD_PROG	"광고프로그램 탐지 : %s\n"
#endif

// 광고프로그램 리스트
char list [TMPLEN][MIN] = {
	"2007 officesystem용 호환기능팩",
	"abouttopbar",
	"abouttopbar-",
	"Absolute Reminder",
	"Ace toolbar",
	"ADDENDUM",
	"Addendum sidebar",
	"Addendum_NM",
	"Addendum-bar",
	"Addendum-nm",
	"addmsidebar",
	"ads",
	"AD-SAFE",
	"AD-Sweeper",
	"Advenced Top C Manager",
	"AD-Zero",
	"afreeca",
	"ahnfgss0.dll",
	"ahnfgss1.dll",
	"ahnsbsb.exe",
	"Ahnsoft",
	"ahnxsds0.dll",
	"ahnxsds1.dll",
	"Air pc",
	"AKInteractive",
	"alkalinesv",
	"Alsearch",
	"ALT C++ Video Flash Activex Manager",
	"ALT C++Video Flash Activex Manager",
	"ANIJ",
	"anti namecheck filter actctrl",
	"AntiAvoid",
	"antiVir",
	"Any tv 무료동영상",
	"AnyCleaner",
	"appis",
	"Application Optimizer",
	"appls",
	"at supporter",
	"Atarget version",
	"atbaddon",
	"AuctionTab",
	"Auto styling Plugin",
	"Babylon toolbar on IE",
	"BabylonObjectInstaller",
	"bacon",
	"baro search",
	"BaroSearch",
	"Better Surf Plus",
	"BiBi Box",
	"bing bar",
	"Bio pc medic",
	"Blekko Search Bar",
	"blueadv",
	"BoanK",
	"boankeeper",
	"boankiller",
	"Boanpro",
	"Bonanza Deals",
	"bpntup",
	"Browse2save",
	"Browser Manager",
	"BrowseToSave",
	"BTControl12DM3 Toolbar for IE",
	"Buddy Search",
	"Bug korea",
	"Bundled software uninstaller",
	"ByToolbar",
	"card21",
	"cash -back",
	"castip",
	"ccleaner",
	"checkboan",
	"checkspeed",
	"checksum",
	"Citrix",
	"classa",
	"clean 119",
	"clean control",
	"Clean I ",
	"cleancontrol",
	"CleanVaccine",
	"cleanx",
	"cleanxup",
	"Clearcom",
	"cleardisk",
	"ClearVaccine",
	"Clear-Vaccine",
	"CleenX",
	"Cleversearchoc",
	"Clickmonster",
	"Clicknsearch",
	"clisopt",
	"clksnrw",
	"CloudEngine",
	"cnpninessys x86",
	"cnptensys x86",
	"cobato",
	"Code 119",
	"Code Killer",
	"Code killer, CodeScan",
	"Code Search",
	"CodeKiler",
	"codeout",
	"CodeScan",
	"CodeSearch",
	"codreg.exe",
	"CoKilri.exe",
	"comboan",
	"CommonSvr",
	"comoXP",
	"Complitly",
	"computer-optima",
	"computeroptimize",
	"computeroptinize",
	"conditionalset",
	"conduit",
	"Conduit Engine",
	"Conduit Seach",
	"Conduit Search",
	"Configdata",
	"ContentSAFER",
	"ContentSAFER fod Wizmax",
	"ContentSAFER for Wizmax",
	"ContinueToSave",
	"Controlspeed",
	"cool edit pro",
	"coolcode",
	"cool-pc",
	"CouponMatcher",
	"CredMgr",
	"crossplat",
	"csmgcdl",
	"csrwndtp",
	"ctdata",
	"CyberBoan",
	"dailypacon sys client x86",
	"Damagia",
	"datamodify",
	"DefaultTab",
	"Defence Vaccine",
	"Di version",
	"Di version 1.0.0 Dual Matching",
	"DirectKeyword2",
	"Disk 1004",
	"DiskBoan",
	"diskscan",
	"Diskster",
	"dll-files.com fixer",
	"dobuycns",
	"dons21_v83",
	"dopot uninstall",
	"DowmManager",
	"DownLoad Get",
	"DownLoadGet",
	"downmanager",
	"downs searchbar",
	"Dr.scan",
	"DreamAD Product",
	"driveragent by esupport.com",
	"drpc",
	"drpcfree",
	"Dr-scan",
	"dr-scan adware & spyware vaccine",
	"Dual Matching",
	"DualMatching",
	"easy on",
	"Easy Search",
	"EasyClean",
	"EasyFavo",
	"EasyFileShare",
	"EasyOn",
	"EasyPop",
	"Easysearchengine",
	"EBcbs Uninstall",
	"ebrowser uninstall",
	"ecleaner",
	"Endisk",
	"enstart",
	"Enumerate Top Search - gt",
	"Enumerate Top Search-gt",
	"Enumerate-nm",
	"EPKI Center EPKIWCtl",
	"EPKI Center EPKIWCtl Control",
	"eps",
	"erwindow(alpha)",
	"Escape 악성코드제거",
	"e-timing VISUAL TS Verifier for Adobe Reader",
	"everyclear",
	"everytoolbar",
	"exactul",
	"explorer open search",
	"EZ catch",
	"ezenjoy",
	"ezurl",
	"Fast Search by Surf Canyon",
	"fastvaccine",
	"favoclick",
	"FavorHost",
	"FBM (즐겨?기트레이아이콘)",
	"File Ham 탐색기",
	"File Type Assistant",
	"FileDown",
	"FileDownload service cocofile",
	"FileDownload service filedol",
	"FileDownload service onefile",
	"Fileget",
	"FileNolja Update Launcher",
	"FileVaccone",
	"Find_Zipcode",
	"findkey",
	"FindTop",
	"FineTop",
	"FineTop, First Click, Freespon uninstall",
	"first click",
	"firstvaccine",
	"FixError for Windows",
	"forgetm",
	"Freespon uninstall",
	"froductline",
	"Funmoods",
	"Funmoods Web Search",
	"Futuresream Client",
	"FutureStream Client",
	"GadgetBox",
	"GadgetBox Updater",
	"Game clean service",
	"Gappl",
	"GBox",
	"Gemmir Supporter",
	"ggemdol",
	"gobugizip",
	"gogoPop",
	"gonet_v249",
	"good2",
	"good2_v117",
	"goodad",
	"gpplayer",
	"grdpop win",
	"Guide0n",
	"Guide0n Uninstall",
	"GuideOn",
	"GuideOn Uninstall",
	"haanweb",
	"hacking free",
	"halfguideon",
	"Happymoney manager",
	"Hellopop",
	"hgmadsearch",
	"Hint",
	"HKstart.exe",
	"Hotclip reader",
	"hotport ",
	"HubGate",
	"HUBGATE Uninstall",
	"HubHelper",
	"IB Updater Service",
	"Icon guide",
	"iconguide",
	"IE ad view system adgugu",
	"IE Search hoowing",
	"IE Support for Windows ",
	"IE tab",
	"IEShow Link",
	"IETAB",
	"iexplorer object service(plus-up)",
	"Iminent",
	"IMinent Toolbar",
	"InboxAce Internet Explorer Toolbar",
	"Indoit(r)Explorer Matched Pop",
	"info Tab",
	"info-green uninstall",
	"infoScan",
	"infowise",
	"infowise interpopsite software",
	"INSafe",
	"INSafeTab",
	"Insidebarr",
	"Intelligent",
	"interezen",
	"Internet Contents Guide",
	"internet direcgo",
	"internet EX search hdvice",
	"internet expiorer clear",
	"internet explorer arlimy",
	"internet explorer guide",
	"internet explorer searcher keywardpop",
	"Internet Explorer Toolbar 4.6 by SweetPacks",
	"Internet Explorer Toolbar 4.7 by SweetPacks",
	"Internet Explorer Webtoon Support",
	"Internet ExplorerGuide Plus",
	"Internet Favorite",
	"internet gold bar client",
	"Internet gold-bar Clien",
	"Internet gold-bar Client",
	"internet ibguide",
	"Internet leFind",
	"Internet linelink Client",
	"Internet Research Support",
	"internet reward sevice(샵모아)",
	"internet service",
	"Internet Service Manager",
	"internet speed",
	"Internet Subjet Client",
	"Internet svbar Client",
	"internet system",
	"InternetDownload",
	"Internetinfos",
	"internetpopsite software",
	"InternetProfessional",
	"InWebOn",
	"IP Error Fix",
	"IPlus",
	"iplus_bu",
	"IPocket",
	"Ipop",
	"ISE",
	"isearch",
	"isink drv",
	"ISP Life",
	"iSrcgRo",
	"iSrchRo",
	"itemmania Funicon",
	"J2J25",
	"J2J25(J2J25.exe)",
	"J2J25.exe",
	"Jangfile",
	"kai for windows sys",
	"KCW Ad Matching",
	"KCW AdMatching",
	"kerboard secure",
	"Kesinfoi",
	"Key perfect",
	"keyboard safety device",
	"KeyCast",
	"KeyMapper",
	"KeyPang",
	"KeyPang version",
	"KeyShape CertRelay",
	"Keyword Search",
	"Keywordfind",
	"Keywordinfo",
	"KeywordTabUninstall",
	"KeywordYac",
	"Kies",
	"Kimspn",
	"Kinucc",
	"Kocoa_v136",
	"kpang uninstall",
	"Kperfect",
	"Kpupdate",
	"kpupdate version",
	"kthcps",
	"KTHOpenSearch",
	"KTM Support",
	"ktmusic 웹 다운로드 모듈",
	"KTPROTECT",
	"kword",
	"lanine clicnt x86 ",
	"lanup",
	"latewene clicnt x86 ",
	"launcelve client x86 ",
	"launten clicnt x86 ",
	"Libar",
	"Libar version",
	"lifeclean",
	"Link Direct",
	"LinkDirect",
	"Live Float",
	"live floot",
	"Live Keys",
	"Live PC",
	"livebrush mini",
	"livecall suite",
	"Liveeasy",
	"Liveeasy ",
	"liveupdater",
	"LocalBox",
	"lucky leap",
	"MawebSAFER_KERIS",
	"Mclean",
	"mclear pc",
	"mclient update soft x86",
	"Media Newssuppot Enter",
	"media vision",
	"MemoryKeeper",
	"mggsearch",
	"Miclient service update x86",
	"micnumber client service x86",
	"Micnumber client service x86 ",
	"Miconsoft",
	"Miconsoft Control management",
	"Micoro Window Capture Openscap",
	"micprovide",
	"micresolution",
	"Micro Keywordpop",
	"Micro Mini MP3 For Windows",
	"Micro NeoWinSearch",
	"micro solution",
	"Micro Visual C 2012 delphi AD",
	"Micro Window Capture opencap",
	"micro_sponsor13",
	"microADscan",
	"Microclient update service x86",
	"MicroCloudEngine",
	"microlient x86",
	"Micronames Multi Langeage Convert Service",
	"Micronames Multi Language Convert Service",
	"Micronames Muti Language Convert Service",
	"microon",
	"micropop",
	"MicroPowerOff",
	"Micros client service x86 ",
	"microsolution",
	"Microupdate client x86",
	"microupdate ninetip x86",
	"Microupwyer x86",
	"microWEBAD",
	"MicroWebAD installer",
	"Microwordlater x86",
	"Moazine Update",
	"MobinDenza",
	"MobinSkills",
	"MobinUsefull",
	"ModernXo",
	"modinland",
	"moodtuner",
	"Mouse Control Client",
	"Mouse Control Service",
	"Mouse Right Button Abler",
	"Movies Toolbar for Chrome",
	"MozenCuto",
	"MozeNumb",
	"MozinPoint",
	"mplanshift",
	"msbuyn",
	"MsEcnt Library",
	"MSmartkey",
	"MSmartpop",
	"Mufree",
	"Multibox Service",
	"multimedia pop",
	"MWguide",
	"Mycashbank",
	"MypcDoctor",
	"mysponsor unistall",
	"nat service",
	"NAT Service 2.3.0.20",
	"NateFinder",
	"nemark explorer",
	"neowebboard55",
	"Net Ip Information Viewer",
	"Netspy",
	"Network ADView",
	"NH Window Show",
	"NoraraInstaller",
	"Norton security scan",
	"nowcomlauncher",
	"npEfdsWCtrl",
	"nprotect",
	"nprotect pc clean",
	"nq supporter",
	"nsviewpro",
	"Nvirus",
	"nwiz",
	"nxtech",
	"Oklotto",
	"Onechu",
	"oneclicksecure",
	"Oneplayer",
	"Openpro",
	"OpentabUninstall",
	"Optimize Application",
	"Optimizer",
	"OptimizerPro",
	"Overture keyword service",
	"palette",
	"PC Cleaner Center",
	"pc cover",
	"PC Game Cleaner Center",
	"pc manager",
	"pc turbo",
	"pc 보안 patch",
	"pc 최적화 clear pc",
	"pc-boan",
	"pc-boom",
	"pcfree",
	"PCM Defender",
	"pc-pro",
	"pc-rador",
	"pc-saver",
	"PCYac",
	"pc도우미2011plus",
	"pc사랑",
	"phpnuke toolbar",
	"pin guide",
	"planet site bar",
	"platkeyword",
	"plusclear",
	"plusup",
	"Pocket-Search",
	"poen shopper",
	"pointbag",
	"popupguide",
	"posttip",
	"powerbackup",
	"powerlink",
	"powerplan",
	"processcontrol",
	"processdataset",
	"Prodess Updater ",
	"prognser",
	"programcnfg",
	"Protected Search",
	"protectinfo",
	"QadSoftware",
	"qualitink ",
	"QuickDownloadService",
	"QuickStores-Toolbar",
	"Radiostar",
	"rbbank",
	"R-cash utility",
	"Real Gcastname",
	"RealCon",
	"realplus",
	"Recentsearch",
	"recfngcontainer",
	"recommeand internet site",
	"Reflection Infomation Client x86",
	"Release mouse r-button protection",
	"remove i-multi",
	"remove web plusup",
	"remove webopu(plusup)",
	"remove winhelper",
	"renewupdate",
	"ReportSP",
	"reservedataset",
	"reservewinset",
	"richcat",
	"rprtsetup",
	"saart updater servicepack",
	"Safe Vaccine",
	"SaveBoan",
	"Save-Boan",
	"SaveShare",
	"saw tv",
	"Search Assistant MocaFlix",
	"Search Assistant SimpleSpeedy ",
	"Search Assistant SoftQuick",
	"Search Assistant WebSearch",
	"search manager",
	"search pop",
	"Search Protect by conduit",
	"Search Protection",
	"SEARCH SPY",
	"Search URL",
	"searchclick",
	"searchlite",
	"SearchNewTab",
	"SearchPack",
	"SearchQ",
	"Searchqu Toolbar",
	"Searchup",
	"secure contents providing system",
	"security interboan",
	"seekmo browser and wowpapers tools",
	"selection search",
	"serchup",
	"share",
	"shop-guide",
	"shopping cashback linkshoper",
	"Shoptopbar",
	"side tab",
	"sidematch",
	"sideoh",
	"sideweb",
	"SISShortcut",
	"Sk-Enabler",
	"SK-Helper",
	"SK-Supporter ",
	"Slick Savings",
	"smart connection tc services",
	"Smart Update Windows Application",
	"SmartMode",
	"SmartopenWeb",
	"SmartSupporter",
	"SmartUtility",
	"SmartWeb",
	"Software Updater",
	"Software Version Updater",
	"sothink video encoder for adobe flash",
	"Speedbooting",
	"speedcure",
	"Speedfile",
	"SpeedSet",
	"SpeedSet, SpeedWindow",
	"speedweb",
	"SpeedWindow",
	"sphelper",
	"sponsor flash windows",
	"Sponsorkeyword Uninstall",
	"sponsormatch Uninstall",
	"spoussorkeyword uninstall",
	"Spowcon Smart service",
	"SProtector",
	"SPY Medic",
	"Spycatch",
	"Spykeep",
	"spysweeper",
	"Ss.Helper",
	"stab",
	"StarPDS Controller System",
	"stip version",
	"stip version 1",
	"suerF and keep",
	"Sun clean",
	"SuperAntiSpyware",
	"Suportloader",
	"surf aNd keeep",
	"SweetIM for Messenger",
	"SweetPacks bundle uninstaller",
	"sysh version",
	"sysh version 1",
	"sysnonclose",
	"system conduit Libaray",
	"system conduit Library",
	"system contkwge uninstall",
	"system count jage uninstall",
	"system count Lab",
	"system je word cnt",
	"system laperclicnt x86 ",
	"system laseveclicnt x86 ",
	"system launcherlcnt x86",
	"System launcherlcnt x86 ",
	"system Linenumber",
	"system mocount",
	"System ntonctrol client x86 ",
	"system numcountelcnt",
	"system numKcount",
	"system numKountelcnt",
	"System power off",
	"system reference guide",
	"system requirements lab CYRI",
	"system sntwenum launcher ",
	"system utilnum launcher",
	"system utilnum launcher ",
	"System utilspae x86 ",
	"system view",
	"system zerword program",
	"systemposy",
	"systemview",
	"tabIE",
	"Tabs provider service ",
	"TabSync",
	"TBEngine",
	"T-Con",
	"The Game Supporter",
	"thefreecoupon",
	"toast Banner",
	"toast version",
	"toast version 1",
	"tomato pack",
	"toobar zero",
	"Tool0n uninstall",
	"toolbar",
	"toolon",
	"ToolOn uninstall",
	"Top Click",
	"Top Util",
	"Topcheker",
	"topguide",
	"TopNews",
	"topsearch",
	"Topspace Windows IE Platform",
	"TopUp",
	"tpnbbs",
	"uiguider",
	"uiguiders",
	"up baduki",
	"up sexymakgo",
	"Update Manager for SweetPacks",
	"updateusercnfg",
	"upgradepc",
	"URL snooper",
	"User dnControler manager",
	"usercnfg",
	"uTControlTEST5 Toolbar for IE",
	"Util launcher",
	"Util Zone",
	"utilauncher",
	"UtilDanawa",
	"utillauncher",
	"Utilocean",
	"utiltop",
	"utiltop Update Guide",
	"utilty systemds launcher",
	"UtilZone",
	"UtiZone",
	"utool Uninstall",
	"uTorrent",
	"vaccine free",
	"Version Checker for Funmoods",
	"viewpoint media player",
	"vikiller",
	"vi-out",
	"virus119",
	"virus-kill",
	"viscan",
	"Visual effect underpop System",
	"visual favorite",
	"visual search",
	"walltab",
	"web AB client modulr",
	"Web Guide",
	"web sniper3a",
	"Web surfing guide",
	"WebCake",
	"WebEdit",
	"Weblauncher for windows xp/2000/2003",
	"WebPri20Server",
	"Webvia",
	"WEBZEN Browser Extension",
	"Wemakeppopclient service update x86 ",
	"werpingt2",
	"WhiteSmoke Search",
	"wide on uninstall",
	"WIMGAPI",
	"win search 3개",
	"Win Search for ozplus",
	"Win Search for rolypop",
	"Win Search for upstech",
	"win shopping icon guide",
	"Winapp for Windows",
	"wincap manager",
	"wincircuslink uninstall",
	"wincommon",
	"Windous Download Manager RapidGet",
	"window at shutdown mgr",
	"window auto turn-off timer",
	"Window Boan Patch",
	"Window Controller",
	"Window DeskTopNote",
	"Window FindKey Controller",
	"Window fortfire",
	"window january3",
	"Window Live Pot Uninstall",
	"Window MovieSearch",
	"window unroll search",
	"Window VirtualKeyboard",
	"Windowguard",
	"Windowns SEvent Style",
	"windows 2000/xp driver for extool-bar",
	"windows 2000/xp navy display tool",
	"windows adaper manager",
	"Windows addenbar",
	"Windows Addendum Lin",
	"windows adpaper Manager",
	"Windows Application Fix Errors",
	"Windows auto turn-off timer",
	"Windows AutoFix",
	"Windows Baro Visit",
	"windows bewenget sys x86 ",
	"windows btwnyfor sys x86 ",
	"windows bupwelev sys x86 ",
	"windows bupwsevty sys x86 ",
	"Windows ButtonGuide",
	"windows bweeighty sys x86 ",
	"Windows cashbackkorea uninstall",
	"windows cashpius",
	"Windows client laendon x86 ",
	"Windows client launcon x86 ",
	"Windows client pbicon x86 ",
	"Windows cloudpop Manager",
	"windows cludpop manager",
	"Windows CM Component",
	"Windows CMania Runtime",
	"windows cnperdsys x86 ",
	"windows cnpesevesys x86 ",
	"windows cntpdssys x86 ",
	"Windows cntpdssys x86(remove only)",
	"windows cntpssys x86",
	"windows cntwesys launcher ",
	"windows conprose guide",
	"windows control bar",
	"Windows dailycon client x86 ",
	"windows ddoki uninstall",
	"Windows Defender Clean",
	"windows desktop widget goorma",
	"Windows Directchicon",
	"Windows Directcon",
	"Windows directsite companent",
	"Windows directweb",
	"windows docQ",
	"Windows domunitool",
	"windows donkey toolbar",
	"Windows doublepoint",
	"Windows download manager rapidget",
	"windows driver for cashontool",
	"windows driver for linkstop",
	"Windows driver for platinum reward",
	"Windows driver for uturnbar",
	"windows drivers for IE security bar",
	"Windows dwnty",
	"windows dynamic shortcut",
	"windows easyhar control",
	"windows elcon runtime",
	"Windows Error Clear",
	"windows event update v.03",
	"Windows extension searchm",
	"Windows fasts toolkit",
	"windows findkey controller",
	"windows findkey Manager",
	"Windows Fix Errors",
	"Windows Fixs",
	"windows for ndp",
	"Windows free-save",
	"windows gcback utility uninstall",
	"Windows Goodday sidebar",
	"Windows IE address security component",
	"windows IE Assistant",
	"Windows IE doumi",
	"windows IE dream pack",
	"Windows IE driver for tbshield",
	"Windows IE linkinside",
	"windows IE opencash",
	"Windows IE Support",
	"Windows IE Top Platform",
	"Windows IE widelink",
	"windows iedoum",
	"windows iedoume",
	"windows iek xsgs uninstall",
	"windows IEprotector Qsystem",
	"windows infoaux",
	"Windows inirtnet expolorer OKtoolbar",
	"windows installer",
	"windows internet explore 7 addon",
	"Windows Internet Service Manager",
	"Windows internet tool s-browser",
	"windows internet tools-browser",
	"windows internet topfind",
	"Windows IP View",
	"Windows Key Pack",
	"Windows lifewisdom",
	"Windows Live Get Driver",
	"windows live search",
	"windows live search pack",
	"Windows Live Updater",
	"windows live winup",
	"Windows machunru toolbar",
	"windows matchlink Manager",
	"Windows mebspebe ",
	"Windows Media Streaming PODCorn",
	"Windows mizane unstall",
	"Windows mouse protection release",
	"Windows Mouse Release",
	"Windows Mouse Service Fix",
	"Windows Multimedialab",
	"Windows mypoints",
	"windows nbupcteisys x86 ",
	"windows nbupmalsys x86 ",
	"Windows nctrolsec client x86 ",
	"Windows NetCross IE Driver",
	"Windows NSAdvance Assist",
	"windows of start yahoo",
	"Windows oneclik",
	"windows onestep system",
	"Windows openpro",
	"windows osearch toolbar",
	"Windows pds update",
	"Windows pendon x86 ",
	"Windows plusbag",
	"Windows pluspack",
	"Windows pointmania",
	"Windows pointplus",
	"Windows PowerTime",
	"windows premiumad package",
	"windows primead-pop",
	"windows purchase helper uninstall",
	"windows repay system",
	"windows rightcilk copy",
	"windows rightclick copy",
	"Windows safe Search",
	"Windows savemode",
	"windows search",
	"Windows search fortruepod",
	"Windows Search Helper Adtrigger",
	"Windows Search Pack",
	"Windows search savecash",
	"Windows search toolbar",
	"Windows security netboan personal firewall",
	"Windows Security personal Firewall",
	"Windows shopconnecter",
	"Windows Shopping Cashback",
	"Windows side searchplus",
	"Windows Sidematch System",
	"windows smart pack",
	"windows smartlink system",
	"windows softwareupdater helper",
	"Windows spclick",
	"windows speeddownload",
	"Windows S-Toolbar for IE",
	"Windows Suggestions",
	"Windows Tab Uninstall",
	"Windows Toastjet",
	"Windows ToolTip",
	"windows tostopo manager",
	"windows tostpop manager",
	"windows uninstall weblink",
	"Windows update Hanacontrol (x86 ko)",
	"Windows Update Hanasecontrol",
	"windows update management service",
	"Windows Update Service",
	"windows URLBAR control",
	"windows urldoumi object",
	"Windows uses of the dpoint",
	"Windows Utilchango Service",
	"windows utilcnt launcher",
	"windows utilcnt launcher ",
	"windows utilworld download center",
	"Windows Visual ad php",
	"windows wcockpit",
	"Windows website controller",
	"windows windowkey Manager",
	"Windows Winerspop",
	"Windows winwool",
	"Windows Wireless Common Service",
	"Windows WIS",
	"Windows xp searchfree",
	"Windows xp/2000/2003 wnl",
	"Windows ziptool",
	"windowsdoja wordsys x86 ",
	"Windowserch Control",
	"windowsLiveprotect",
	"windowsRegistry",
	"Windows-site security(ks82831)",
	"windowsviewcon",
	"windows-webprotect",
	"WindowSystem",
	"windowviewcon uninstall",
	"windowviewcon(gooorma) uninstall",
	"Windowviewcon(goorma) uninstall",
	"winggo",
	"WingView",
	"Winhelp",
	"WinP online control",
	"Winpro",
	"winreconfig",
	"WinScare",
	"WinSearchTop",
	"WinsHelp",
	"WinsManager",
	"WinSmartTop",
	"WinsPop",
	"winzero uninstall",
	"Wise Table version",
	"WiseGrid ActiveX",
	"wisepopup",
	"Wizeni",
	"Wizsearch",
	"wowlink",
	"Wpu for windows",
	"WS-Enabler",
	"xecure speller application",
	"Xecure URL link control",
	"xk_winxp/2000 최적화",
	"xpeadup7",
	"x-ray 툴바",
	"xvid share uninstall",
	"xxxx I-nav xxxxx",
	"yabisearch",
	"YahooStartPage Setup ",
	"yessearch",
	"Yontoo 1.12.02",
	"Yontoo 1.12.03",
	"zero spy",
	"zzixx::Daolim ",
	"공유브라우져",
	"넷보안관",
	"넷스파이",
	"뉴스플러스",
	"닥터바이러스",
	"닥터클린",
	"디스크스터",
	"바이스캔",
	"바이아웃",
	"바이킬러",
	"백신코리아",
	"버튼가이드",
	"보너스팩",
	"비패스트",
	"서치삽",
	"서치웹",
	"쇼핑 스트리트,11번가 도구모음 아이콘",
	"스파이맵",
	"스파이캐치",
	"스파이헌터 NEO",
	"씨네락 오락실",
	"아이팝",
	"아프리카TV",
	"악성코드안전장치 AD-LOCK",
	"악성코드애드웨어치료",
	"악성코드치료 stop",
	"악성코드치료stop",
	"애드스나이퍼",
	"엠군서치툴바",
	"오픈쇼퍼",
	"원클릭시큐어",
	"원클릭씨큐어",
	"윈도우 종료 매니저 업데이트",
	"이수비 무료악성코트 치료기",
	"이지캐치",
	"이지툰 서치",
	"자료실 업데이트 매니저",
	"전자신고 원천세",
	"전자신고 종합소득세 2011",
	"전자신고 종합소득세중간예납 2011",
	"전자신고작성 2005",
	"조이유틸",
	"증명서 위변조 검증 프로그램(국세청)",
	"지급명세서변환 2011_v10",
	"지우개",
	"최근검색(ggemdol)",
	"케이워드",
	"클럽박스 파일전송 관리자",
	"클리어디스크",
	"탑클릭-topclik",
	"프레앙 p2p",
	"프리미어툴바",
	"피디박스/클럽박스 제거",
	"하얀 pc",
	"한국전력 사이버지점 발급프로그램"
};

// 배열의 길이 찾아주는 함수. 광고프로그램 리스트는 길이가 기나 내용을 추가 할 수도 있으므로 동적으로 구현.
int FindLength(){
	for (int i = 0; i < TMPLEN; i++) if(strcmp(list[i], "\0") == 0) return i;
}

int main(int argc, char *argv[]) {
	FILE	*fp, *fp2, *fp3;						// 파일 포인터 변수
	char	buff[MAX], buff2[MAX], buff3[MAX];		// 입력받을 버퍼 배열
	char	cmd[MIN];								// cmd 명령어 저장할 배열
	char	uninstall[MAX] = "\0";					// uninstall 파일 주소 받을 배열
	char 	*pch;									// 문자열 치환할때 쓸 변수
	int		line		= 0;						// 기타 count 및 flag 관련 변수
	int		flag		= 0;						// 
	int		flag_A		= 0;						// 
	int		DisP_or_p	= 0;						// 

	// 레지스트리값 토대로 리스트 추출. 이때 system함수로 나오는 결과값은 모두 nul로 보냄.
	printf(EXTR_PROG_LIST);
	system(CMD_TITLE);
	system(REG64);
	system(REG32);
	system(REG_PRODUCTS);
	// result.txt 파일을 빈 값으로 만듬. 리눅스에서 touch와 같지만 파일 존재시 0바이트로 만듬.
	system(NEW_RESULT_TXT);
	fp	= fopen(RESULT_TXT, "wt");
	if (fp != NULL) {
		fp2	= fopen(REG_TXT, "r");
		if (fp2 == NULL) {
			MessageBox(NULL, N_REG_TXT, TITLE, MB_OK | MB_ICONHAND); 
			fclose(fp); 
			system(DEL_RESULT_TXT); 
			return 0; 
		}
		else {
			// result.txt에다 프로그램 이름들만 크롤링
			while(fgets(buff, ONELINE, fp2)){
				if 		(strstr(buff, FIND_STR) || strstr(buff, FIND_STR2)) fprintf(fp, buff);
				else	continue;
			}
		}
	}
	else {
		MessageBox(NULL, N_RESULT_TXT, TITLE, MB_OK | MB_ICONHAND); 
		system(DEL_REG_TXT); 
		return 0;
	}
	fclose(fp);
	
	// 설치된 프로그램 리스트 파일 불러오기
	printf(CMF_PROG);
	fp	= fopen(RESULT_TXT, "r");
	
	// result파일 출력
	if		(fp == NULL) { 
		MessageBox(NULL, N_REG_TXT, TITLE, MB_OK | MB_ICONHAND); 
		fclose(fp2); 
		return 0; 
	} 
	else	{
		for (int i = 0; i < 50; i++) printf("="); printf(PROG_LIST);
		for (int i = 0; i < 50; i++) printf("="); printf("\n");
		
		// 프로그램 목록 띄우기
		while (fgets(buff, MAX, fp)) {
			if 		(strstr(buff, CHG_BEFORE))  pch = strstr(buff, CHG_BEFORE); // "DisplayName" 을
			else if (strstr(buff, CHG_BEFORE2))	pch = strstr(buff, CHG_BEFORE2);			
			strncpy(pch, CHG_AFTER, 17);						// " - ProgramName : "으로 바꿈
			for (int i = 17; i < MAX; i++) buff[i] = buff[i+10];		// 글자 당겨오는 부분. (ex. "123program" -> "program")
			printf("%s", buff); line++;
		}
		printf(CONFIRM_N_PROG, line);
		
		// list와 result파일 비교해서 광고프로그램 추출
		printf(CMP_PROG);
		for (int i = -1; i < FindLength(); i++) {
			while (fgets(buff, MAX, fp)) {
				
				//printf("%s와 %s 비교\n",buff, buff2);
				if (strstr(buff, list[i]) != NULL) {
					printf(DETECT_AD_PROG, list[i]); flag++;
					
					int check = MessageBox(NULL, "프로그램을 최적화 하시겠습니까?", TITLE, MB_YESNOCANCEL | MB_ICONQUESTION);
					if (check == IDCANCEL)	{
						MessageBox(NULL, CAN_PROG, TITLE, MB_OK | MB_ICONASTERISK); 
						fclose(fp); fclose(fp2); system(DEL_RESULT_TXT); system(DEL_REG_TXT); return 0;
					}
					else if (check == IDYES)	{
						
						// uninstall 배열 초기화. 이거 안하면 uninstallString 긴거 나왔을때 다음 프로그램까지 영향 미침.
						for (int i = 0; i < MAX; i++) uninstall[i] = '\0';
						
						// 레지스트리값에서 uninstallString(삭제프로그램 경로)을 찾음
						rewind(fp2);
						while 	(fgets(buff2, ONELINE, fp2))
							if	(strstr(buff2, list[i]) != NULL)
								while	(fgets(buff3, ONELINE, fp2))
									if	(strstr(buff3, UNINS) != NULL && strstr(buff3, QUNINS) == NULL) {
										for(int i = 0; buff3[i+33] != 0; i++) uninstall[i] = buff3[i+33]; break;
									}
									else if (strstr(buff3, QUNINS) != NULL) {
										for(int i = 0; buff3[i+38] != 0; i++) uninstall[i] = buff3[i+38]; break;
									}
	
						// uninstall 경로에 "" 맞춰주고 인자값까지 잘 들어가게 하는 부분
						for	(int i = 0; i < MAX; i++)	{
							if	(uninstall[0] != '\"')	{
								if	(i >= 5 && uninstall[i-4] == '.' && uninstall[i-3] == 'e' && uninstall[i-2] == 'x' && uninstall[i-1] == 'e') {
									memmove(uninstall+i+1, uninstall+i, sizeof(uninstall)-i);
									uninstall[i] = '"'; i++;
								}
								
							// flag_A로 uninstallString 맨 앞에 "가 있는지 없는지 여부 확인. 있으면 flag_A = 1.
							} else { flag_A = 1; break; }
						}
						
						// cmd.bat에 삭제할 명령어들 fprintf로 넣고 실행.
						system(NEW_CMD_BAT);
						fp3 = fopen(CMD_BAT, "w");
						if 		(fp3 == NULL) { printf(N_CMD_BAT); fclose(fp); fclose(fp2); return 0; } 
						else	{
							if	(flag_A != 1) fprintf(fp3, "\"");
							fprintf(fp3, uninstall);
							fclose(fp3); flag_A = 0; system(CMD_BAT_NUL);
						}
					}
				} else continue;
			}
			
			// fp 커서를 제일 처음으로 돌림. 그래야 프로그램끼리 비교할 수 있음.
			rewind(fp);
		}
	}
	fclose(fp);
	if (fp2 != NULL) fclose(fp2);
	printf(INSP_COMPLETE);
	
	if	 (flag == 0) MessageBox(NULL, NO_AD_PROG, TITLE, MB_OK | MB_ICONASTERISK);
	else {
		char		result[MIN] = { CONFIRM_PROG };
		char		Result[MIN];
		itoa		(flag, Result, 10);
		strcat		(Result, result);
		MessageBox	(NULL, Result, TITLE, MB_OK | MB_ICONASTERISK);
	}
	
	// 필요없는 파일들 삭제
	if (uninstall[0] != '\0') system(DEL_CMD_BAT);
	system(DEL_RESULT_TXT); 
	system(DEL_REG_TXT);
	return 0;
}
